# Generated by Django 4.2.5 on 2023-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_upload', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
