# Generated by Django 4.2.5 on 2023-09-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonicapp', '0004_pdfile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
