# Generated by Django 4.2.5 on 2023-09-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonicapp', '0005_rename_user_id_pdfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfile',
            old_name='user',
            new_name='auth_user',
        ),
    ]
