# Generated by Django 4.2.5 on 2023-09-22 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonicapp', '0006_rename_user_pdfile_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfile',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='pdfile',
            name='user',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
