# Generated by Django 4.2.5 on 2023-09-22 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonicapp', '0007_remove_pdfile_auth_user_pdfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
