# Generated by Django 4.2.5 on 2023-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicapp', '0008_alter_pdfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfile',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=200),
        ),
    ]
